// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/26/2026, 1:24:30 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/plugins/**/*.{js,ts,mjs}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/utils/**/*.{js,ts,mjs}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/composables/**/*.{js,ts,mjs}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mattcamp/MattDev/fm-vue-nuxt-starter/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;